pj1/app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('ipaddress/', views.ipaddress, name='ipaddress'),
	path('ipaddress/change/<int:ipaddress_id>/', views.ipaddress_change, name='ipaddress_change'),
]

pj1/pj1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('app1/', include('app1.urls')),
]

pj1/app1/models.py
from django.db import models

class Ipaddress ( models.Model):

	status_list = (
		('in_use', 'in use'),
		('available', 'available'),
		('not_available', 'not available')
	)
	ipaddress = models.GenericIPAddressField(verbose_name='IP address', unique=True)
	status = models.CharField(verbose_name='Status', choices=status_list, max_length=16)
	description = models.CharField(verbose_name='Discription', blank = True, max_length=255)

	def __str__(self):
		return self.ipaddress

pj1/app1/forms.py
from django.forms import ModelForm
from app1.models import Ipaddress

class IpaddressForm(ModelForm):
    class Meta:
        model = Ipaddress
        fields = ('id', 'ipaddress', 'status', 'description')

pj1/app1/views.py
from django.shortcuts import render , get_object_or_404, redirect
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from app1.models import Ipaddress

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def ipaddress(request):
    # データベース上のIPアドレス情報を配列型で取得
    ipaddresses = Ipaddress.objects.all().order_by('id')

    return  render(
		request,
        'ipaddress.html', # テンプレート名を指定
        {'ipaddresses' : ipaddresses }, # 取得したIPアドレス情報をテンプレート内の変数に代入
        )

def ipaddress_change(request, ipaddress_id=None):

    if ipaddress_id:
        ipaddress =  get_object_or_404(Ipaddress, pk=ipaddress_id)
    else:
        ipaddress = Ipaddress()

    if request.method == 'POST':
        # 基本的にPOSTが推奨される
        form = IpaddressForm(request.POST, instance=ipaddress)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('app1:ipaddress')
    else:
        # GETの場合はこちらを実行
        form = IpaddressForm(instance=ipaddress)

    return  render(
		request,
        'ipaddress_change.html',
        dict(form=form, ipaddress_id=ipaddress_id),
        )

pj1/app1/templates/ipaddress.html
{% load staticfiles %}

<!-- Adjust  bootstrap  navbar -->
body { padding-top: 40px; }

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>App1</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">App1</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">IP address</a></li>
            <li><a href="#">Function 2</a></li>
            <li><a href="#">Function 3</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <h1 class="page-header">IP address</h1>
        <table class="table table-striped table-bordered">

            <thead>
                <tr>
                    <td>ID</td>
                    <td>IP address</td>
                    <td>Status</td>
                    <td>Description</td>
                    <td>Function</td>
                </tr>
            </thead>
            <tbody>
                {% for ipaddress in ipaddresses %}
                <tr>
                    <td>{{ ipaddress.id }}</td>
                    <td>{{ ipaddress.ipaddress }}</td>
                    <td>{{ ipaddress.status }}</td>
                    <td>{{ ipaddress.description }}</td>
                    <td>
                        <a href="{% url 'app1:ipaddress_change' ipaddress_id=ipaddress.id  %}" class="btn btn-default btn-sm">Change Status</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div><!-- /.container -->


  </body>
</html>

pj1/app1/templates/ipaddress_change.html
{% load staticfiles %}

<!-- Adjust  bootstrap  navbar -->
body { padding-top: 40px; }

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>App1</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">App1</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">IP address</a></li>
            <li><a href="#">Function 2</a></li>
            <li><a href="#">Function 3</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <h3 class="page-header">Change Status</h3>
      <form action="" method="post" class="form-horizontal" role="form">
          {% csrf_token %}
          {{ form }}
          <div class="form-group">
            <div class="container">
                <button type="submit" class="btn btn-primary">Change Status</button>
                <a href="{% url 'app1:ipaddress' %}" class="btn btn-default btn-sm">Back</a>
            </div>
          </div>
      </form>
    </div><!--/.nav-collapse -->

  </body>
</html>